#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# 2016-11-21 
# Build script for SimpleTest Xcode project


BuildXcodeProjectForTarget()
{
	printf "${FUNCNAME[0]}\n"
	
	local projectName=$1
	local targetName=$2
	local config=$3
	local configPath=$4

	xcodebuild \
		-project ${projectName} \
		-target ${targetName} \
			-configuration ${config} \
			CONFIGURATION_BUILD_DIR=${configPath} \
			clean build | xcpretty
	# if you want to use egrep instead of xcpretty
	#| egrep -A 5 "(error|warning):"
	
}

SetupVariables()
{
	CONFIG=Debug
	CURRENTPATH=${PWD}
	cd ${ABSOLUTE_PATH}
	BUILDPATH=${PWD}/xcbuild
	cd ../..
	BASEPATH=${PWD}
}

BuildFrameworks()
{
	cd ${BASEPATH}/Renderer
	local frameworkBuildPath=${BUILDPATH}/Products/${CONFIG}/Frameworks
	BuildXcodeProjectForTarget Renderer.xcodeproj Renderer ${CONFIG} ${frameworkBuildPath}
		
	cd ${BASEPATH}/RuntimeCompiler
	BuildXcodeProjectForTarget RuntimeCompiler.xcodeproj RuntimeCompiler ${CONFIG} ${frameworkBuildPath}

	cd ${BASEPATH}/RuntimeObjectSystem
	BuildXcodeProjectForTarget RuntimeObjectSystem.xcodeproj RuntimeObjectSystem ${CONFIG} ${frameworkBuildPath}

	cd ${BASEPATH}/Systems
	BuildXcodeProjectForTarget Systems.xcodeproj Systems ${CONFIG} ${frameworkBuildPath}
	
	cd ${BASEPATH}/External/libRocket/Build
	BuildXcodeProjectForTarget Rocket.xcodeproj RocketControlsOSX ${CONFIG} ${frameworkBuildPath}
	BuildXcodeProjectForTarget Rocket.xcodeproj RocketDebuggerOSX ${CONFIG} ${frameworkBuildPath}
}

BuildSimpleTest()
{
	cd ${ABSOLUTE_PATH}
	local buildPath=${BUILDPATH}/Products/${CONFIG}
	BuildXcodeProjectForTarget SimpleTest.xcodeproj SimpleTest ${CONFIG} ${buildPath}
}

CopyFrameworksAndLibs()
{
	cd ${ABSOLUTE_PATH}
	cp -R ${BUILDPATH}/Products/${CONFIG}/Frameworks ${BUILDPATH}/Products/${CONFIG}/SimpleTest.app/Contents/Frameworks
}

main()
{
	SetupVariables
	BuildFrameworks
	BuildSimpleTest
	CopyFrameworksAndLibs
}

ABSOLUTE_SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
ABSOLUTE_PATH=`dirname ${ABSOLUTE_SCRIPT_PATH}`

main
