#!/usr/bin/env bash

source SimpleTestBuild.sh

# 2016-11-21 
# Build script for SimpleTest Xcode project

BuildSimpleTest()
{
	printf "${FUNCNAME[0]}\n"
	
	cd ${ABSOLUTE_PATH}
	local buildPath=${BUILDPATH}/Products/${CONFIG}
	BuildXcodeProjectForTarget SimpleTest.xcodeproj SimpleTest ${CONFIG} ${buildPath}
}

main()
{
	printf "${FUNCNAME[0]}\n"
	
	SetupVariables Debug
	BuildFrameworks ${BASEPATH}
	BuildSimpleTest
	CopyFrameworksAndLibs
}

ABSOLUTE_SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
ABSOLUTE_PATH=`dirname ${ABSOLUTE_SCRIPT_PATH}`

main
