#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# 2016-11-21 
# Build script for SimpleTest Xcode project


BuildXcodeProjectForTarget()
{
	printf "${FUNCNAME[0]}\n"
	
	local projectName=$1
	local targetName=$2
	local config=$3

	xcodebuild \
		-project ${projectName} \
		-target ${targetName} \
			-configuration ${config} \
			CONFIGURATION_BUILD_DIR=${BUILDPATH}/${config} \
			clean build | xcpretty
	# if you want to use egrep instead of xcpretty
	#| egrep -A 5 "(error|warning):"
	
}

SetupPathVariables()
{
	CURRENTPATH=${PWD}
	cd ${ABSOLUTE_PATH}
	BUILDPATH=${PWD}/xcbuild
	cd ../..
	BASEPATH=${PWD}
}

main()
{
	SetupPathVariables
	local config=Debug
	cd ${BASEPATH}/Renderer
	BuildXcodeProjectForTarget Renderer.xcodeproj Renderer ${config}
		
	cd ${BASEPATH}/RuntimeCompiler
	BuildXcodeProjectForTarget RuntimeCompiler.xcodeproj RuntimeCompiler ${config}

	cd ${BASEPATH}/RuntimeObjectSystem
	BuildXcodeProjectForTarget RuntimeObjectSystem.xcodeproj RuntimeObjectSystem ${config}

	cd ${BASEPATH}/Systems
	BuildXcodeProjectForTarget Systems.xcodeproj Systems ${config}
	
	cd ${BASEPATH}/External/libRocket/Build
	BuildXcodeProjectForTarget Rocket.xcodeproj RocketControlsOSX ${config}
	BuildXcodeProjectForTarget Rocket.xcodeproj RocketDebuggerOSX ${config}
		
	cd ${ABSOLUTE_PATH}
	BuildXcodeProjectForTarget SimpleTest.xcodeproj SimpleTest ${config}
}

ABSOLUTE_SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
ABSOLUTE_PATH=`dirname ${ABSOLUTE_SCRIPT_PATH}`

main
